// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2906.SpanawayLakeSentinels.subsystems;

import org.usfirst.frc2906.SpanawayLakeSentinels.RobotMap;


import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc2906.SpanawayLakeSentinels.OI;
import org.usfirst.frc2906.SpanawayLakeSentinels.Robot;

/**
 *
 */
public class armDrive extends Subsystem {
   
	
    SpeedController rotation = RobotMap.rotation;
    

    public void initDefaultCommand() {

    	rotation = RobotMap.rotation;
    	rotation.set(Robot.oi.getJoystick2Y());
    }
    
    public void armUp(){
    	rotation.set(RobotMap.upArm);
    	
    }
    public void armDown(){
    	rotation.set(RobotMap.downArm);
    	
    }
    public void armStop(){
    	rotation.set(RobotMap.stopArm);
    	
    }
    public void armIdle(){
    	rotation.set(RobotMap.idleArm);
    }
    public void autoRaise(){
    	rotation.set(.5);
    }
    public void autoStop(){
    	rotation.set(0);
    	
    }
    public void lowPower(){
    	rotation.set(RobotMap.powerLow);
    }
    
 
    public void driveArm(){
    	
    	rotation.set(Robot.oi.getJoystick2Y());
    }
    public void toFire(){
    	rotation.set(RobotMap.shootingPosition);
    }
}

