// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2906.SpanawayLakeSentinels.subsystems;

import org.usfirst.frc2906.SpanawayLakeSentinels.RobotMap;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Pneumatics extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    
    
    DoubleSolenoid armGrip;
    Solenoid testPiston1;
    Solenoid testPiston2;
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMANDlay
    	armGrip = RobotMap.ballFire;
    	testPiston1 = RobotMap.testPiston1;
    	testPiston2 = RobotMap.testPiston2;
    	
    }
    public void Open(){
    	armGrip.set(Value.kForward);
    }
    
    public void Close(){
    	armGrip.set(Value.kReverse);
    }
    
    public void Off(){
    	armGrip.set(Value.kOff);
    }

    public void testOpen1(){
    	testPiston1.set(true);
    }
    
    public void testClose1(){
    	testPiston1.set(false);
    }
    
    public void testOpen2(){
    	testPiston2.set(false);
 	
    }
    
    public void testClose2(){
    	testPiston2.set(true);
    }
    
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    
    }


