// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2906.SpanawayLakeSentinels.subsystems;

import org.usfirst.frc2906.SpanawayLakeSentinels.RobotMap;


import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc2906.SpanawayLakeSentinels.OI;
import org.usfirst.frc2906.SpanawayLakeSentinels.Robot;
import edu.wpi.first.wpilibj.Relay;

/**
 *
 */
public class testRelay extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOT+BUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
   
	
    Relay testRelay = RobotMap.testSpike;
    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    	
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    	testRelay = RobotMap.testSpike;
    }
    
	public void driveSpikeForward(){
		testRelay.set(Relay.Value.kForward);;
	}
    
	public void driveSpikeReverse(){
		testRelay.set(Relay.Value.kReverse);
	}
	
	public void spikeOff(){
		testRelay.set(Relay.Value.kOff);
	}
	
}

